// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHecP2hzPVn8xZtdiFe1IBRh216IC7gGU',
    appId: '1:961262722277:web:9b96ad74277b063acec80c',
    messagingSenderId: '961262722277',
    projectId: 'food-delivery-app-7e7ab',
    authDomain: 'food-delivery-app-7e7ab.firebaseapp.com',
    storageBucket: 'food-delivery-app-7e7ab.firebasestorage.app',
    measurementId: 'G-W6F23GTC65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOtzo6-v_pESNWElwllk_BJMx_RkXgNkg',
    appId: '1:961262722277:android:19177bac69f37907cec80c',
    messagingSenderId: '961262722277',
    projectId: 'food-delivery-app-7e7ab',
    storageBucket: 'food-delivery-app-7e7ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEubnSUMMq1fK5dC2FFAPewB4aSIHX8gk',
    appId: '1:961262722277:ios:522949c4aa8cc85acec80c',
    messagingSenderId: '961262722277',
    projectId: 'food-delivery-app-7e7ab',
    storageBucket: 'food-delivery-app-7e7ab.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEubnSUMMq1fK5dC2FFAPewB4aSIHX8gk',
    appId: '1:961262722277:ios:522949c4aa8cc85acec80c',
    messagingSenderId: '961262722277',
    projectId: 'food-delivery-app-7e7ab',
    storageBucket: 'food-delivery-app-7e7ab.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHecP2hzPVn8xZtdiFe1IBRh216IC7gGU',
    appId: '1:961262722277:web:3851049698261b28cec80c',
    messagingSenderId: '961262722277',
    projectId: 'food-delivery-app-7e7ab',
    authDomain: 'food-delivery-app-7e7ab.firebaseapp.com',
    storageBucket: 'food-delivery-app-7e7ab.firebasestorage.app',
    measurementId: 'G-29WX75V060',
  );
}
